"use client";

import React from 'react';
import { motion } from 'framer-motion';
import { FileText, CheckCircle2, AlertCircle } from 'lucide-react';

const fadeInUp = {
    initial: { opacity: 0, y: 30 },
    animate: { opacity: 1, y: 0 },
    transition: { duration: 0.8, ease: [0.16, 1, 0.3, 1] }
};

export default function TermsPage() {
    return (
        <div className="bg-[#F7F9FA] min-h-screen">
            <div className="max-w-4xl mx-auto px-6 lg:px-12 py-24">
                <motion.div
                    initial="initial"
                    animate="animate"
                    variants={{ animate: { transition: { staggerChildren: 0.05 } } }}
                >
                    <motion.div variants={fadeInUp} className="inline-flex items-center gap-2 px-3 py-1 bg-[#32B5A4]/10 border border-[#32B5A4]/20 rounded-full mb-8">
                        <FileText size={14} className="text-[#32B5A4]" />
                        <span className="text-[10px] font-bold uppercase tracking-wider text-[#32B5A4]">Service Agreement</span>
                    </motion.div>

                    <motion.h1
                        variants={fadeInUp}
                        className="text-5xl font-bold tracking-tight text-[#0C2340] mb-8"
                    >
                        Terms of Service
                    </motion.h1>

                    <motion.p variants={fadeInUp} className="text-sm text-slate-500 font-bold uppercase tracking-widest mb-16">
                        Last Updated: January 30, 2026
                    </motion.p>

                    <div className="prose prose-slate max-w-none prose-headings:text-[#0C2340] prose-p:text-slate-700 prose-p:font-medium prose-p:leading-relaxed">
                        <motion.section variants={fadeInUp} className="mb-16">
                            <h2 className="text-2xl font-bold mb-6">1. Acceptable Use</h2>
                            <p>
                                By accessing Solar Payback, you agree to use our calculators and research guides for personal, non-commercial purposes only. Any automated scraping or harvesting of our ROI engine data is strictly prohibited.
                            </p>
                        </motion.section>

                        <motion.section variants={fadeInUp} className="mb-16 p-8 bg-amber-50 border border-amber-200 rounded-3xl">
                            <div className="flex gap-4">
                                <AlertCircle size={24} className="text-amber-600 shrink-0" />
                                <div>
                                    <h3 className="text-lg font-bold text-amber-900 mb-2">Disclaimer: Estimate Only</h3>
                                    <p className="text-sm text-amber-800 leading-relaxed">
                                        All projections generated by Solar Payback are estimates based on historical data and current utility averages. Actual figures may vary based on weather patterns, specific roof orientation, and future utility policy changes. Consult with a certified solar engineer before making investment decisions.
                                    </p>
                                </div>
                            </div>
                        </motion.section>

                        <motion.section variants={fadeInUp} className="mb-16">
                            <h2 className="text-2xl font-bold mb-6">2. Intellectual Property</h2>
                            <p>
                                All content, including logic formulations, UI components, and technical research articles, is the intellectual property of Solar Payback. Reproduction without express written consent is prohibited.
                            </p>
                        </motion.section>

                        <motion.section variants={fadeInUp} className="mb-16">
                            <h2 className="text-2xl font-bold mb-6">3. Third-Party Links</h2>
                            <p>
                                Our research library may contain links to government sites or technical journals. We are not responsible for the accuracy or privacy practices of these external domains.
                            </p>
                        </motion.section>

                        <motion.section variants={fadeInUp} className="mb-16">
                            <h2 className="text-2xl font-bold mb-6">4. Modifications</h2>
                            <p>
                                We reserve the right to update these terms at any time. Continued use of the platform after updates constitutes acceptance of the new terms.
                            </p>
                        </motion.section>
                    </div>
                </motion.div>
            </div>
        </div>
    );
}
